CREATE TABLE IF NOT EXISTS usuarios(
    usuarioid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rol text NOT NULL CHECK (rol <> ''),
    nombre text NOT NULL CHECK (nombre <> ''),
    email text NOT NULL CHECK (email <> ''),
    tipo_documento text NOT NULL CHECK (tipo_documento <> ''),
    nro_documento text NOT NULL CHECK (nro_documento <> ''),
    password text NOT NULL CHECK (password <> ''),
    estado boolean NOT NULL DEFAULT true,
    createAt date NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS personajes(
    personajeid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL CHECK (nombre <> ''),
    edad integer NOT NULL,
    peso float NOT NULL,
    historia text NOT NULL CHECK (historia <> ''),
    imagen bytea,
    estado boolean NOT NULL DEFAULT true,
    createAt DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS peliculaserie(
    peliculaserieid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    titulo text NOT NULL CHECK (titulo <> ''),
    fecha_creacion DATE NOT NULL,
    calificacion integer NOT NULL,
	tipo char CHECK ( tipo in ('p','s') ),
    imagen bytea,
	genero text NOT NULL CHECK (titulo <> ''),
    estado boolean NOT NULL DEFAULT true,
    createAt DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE personajes_peli_serie (
  id_peli_serie    int REFERENCES peli_serie (id_peli_serie) ON UPDATE CASCADE ON DELETE CASCADE
, id_personajes int REFERENCES personajes (id_personajes) ON UPDATE CASCADE
, amount     numeric NOT NULL DEFAULT 1
, CONSTRAINT personajes_peli_serie_pkey PRIMARY KEY (id_peli_serie, id_personajes)  -- explicit pk
);
/*precarga de datos */

/*USUARIOS */
INSERT INTO usuarios(nombre, email, tipo_documento, nro_documento, password) 
VALUES('Edward Rodriguez', 'edward.rodrez@gmail.com', 'CI', '1.111.111-1', '123');
INSERT INTO usuarios(nombre, email, tipo_documento, nro_documento, password) 
VALUES('Jorge Martinez', 'jorge.martinez@example.com', 'CI', '1.111.111-2', '123');
INSERT INTO usuarios(nombre, email, tipo_documento, nro_documento, password) 
VALUES('Martin Viera', 'martin.viera@example.com', 'CI', '1.111.111-3', '123');

/*PERSONAJES */
INSERT INTO personajes(nombre, edad, peso, historia) 
VALUES('Mickey Mouse', 10, 23.2, 'Historia de Mickey Mouse...');
INSERT INTO personajes(nombre, edad, peso, historia) 
VALUES('Ariel', 16, 40.44, 'Historia de Ariel...');
INSERT INTO personajes(nombre, edad, peso, historia) 
VALUES('Minnie Mouse', 10, 19.33, 'Historia de Minnie Mouse...');
INSERT INTO personajes(nombre, edad, peso, historia) 
VALUES('Pato Darkwing', 36, 30.84, 'Historia de Pato Darkwing...');
INSERT INTO personajes(nombre, edad, peso, historia) 
VALUES('Cruella de Vil', 40, 53.33, 'Historia de Cruella de Vil...');

/*PELICULAS*/
INSERT INTO peli_serie(titulo, fecha_creacion, calificacion, genero, tipo) 
VALUES('101 dálmatas', '1973/12/31', 3, 'Comedia', 'p');
INSERT INTO peli_serie(titulo, fecha_creacion, calificacion, genero, tipo) 
VALUES('Aladdin', '1969/07/29', 3,'Comedia', 'p');
INSERT INTO peli_serie(titulo, fecha_creacion, calificacion, genero, tipo) 
VALUES('Alicia en el país de las maravillas',  '1973/12/31', 3,'Comedia', 'p');

/*SERIES*/
INSERT INTO peli_serie(titulo, fecha_creacion, calificacion, genero, tipo) 
VALUES('La banda del patio', '1973/12/31', 3,'Comedia', 's');
INSERT INTO peli_serie(titulo, fecha_creacion, calificacion, genero, tipo) 
VALUES('Darkwing Duck', '1960/09/30', 3,'Comedia','s');
INSERT INTO peli_serie(titulo, fecha_creacion, calificacion, genero, tipo) 
VALUES('Gargoyles: Héroes mitológicos', '1963/11/18', 3, 'Comedia','s');
INSERT INTO peli_serie(titulo, fecha_creacion, calificacion, genero, tipo) 
VALUES('Patoaventuras', '1960/12/28', 3,'Comedia', 's');

/*PELICULAS O SERIES Y SUS PERSONAJES */
INSERT INTO personajes_peli_serie(id_peli_serie, id_personajes) 
VALUES(3,5);
INSERT INTO personajes_peli_serie(id_peli_serie, id_personajes) 
VALUES(7,4);